### ISSUE TITLE
English Study

### ISSUE THREAD

**Issue by xlotech** [Meigyoku-Thmn/LacVietExtract#1]
Data từ điển đã được public từ lâu nhưng em không biết cách mọi người có thể reverse cho đến khi tìm được repo của anh, từ đó tìm hiểu thêm frida, hook api, có thể biết rằng khá khó và tốn thời gian, em có tìm hiểu qua frida để reverse data của bộ english study 4.0 nhưng vẫn chưa hoàn chỉnh, data được lưu trong 1 file index và 1 file data, em chỉ reverse được 1 phần dựa trên repo này: http://hocanhvan.sourceforge.net/, nếu có thời gian anh có thể gợi ý thêm không, cảm ơn anh.

**Comment by Meigyoku-Thmn** [comment]
Thực tế frida chỉ là công cụ hỗ trợ trace bằng code injection (thông qua Javascript) thôi bạn, để reverse thì vẫn cần phải có kỹ thuật reverse.
Như mình thì dùng frida để trace xem từ điển nó đọc file qua các bước nào: in ra file log xem nó bắt đầu đọc từ đâu, seek trong file thế nào, mỗi lần đọc bao nhiêu byte, có thể in stacktrace ở một bước nào đó, v.v.
Thông tin thu thập được sẽ được sử dụng làm đầu mối để reverse, tool để dissasemble thì nhiều, như IDA Pro, OllyDbg, x64dbg, v.v.
Lặp lại vòng lặp Frida - Dissasembler cho đến khi tìm ra quy luật đọc file thôi.
Project này của mình nó khá là mang tính cá nhân, mình nổi hứng làm chỉ vì... không copy được chữ ra khỏi Lạc Việt để tra cứu thêm thôi à. Có thể sau khi xong project này (hiện tại mình còn chưa viết tài liệu giải thích) thì có thể mình sẽ xem qua, nhưng không hứa hẹn được gì cả.

**Comment by xlotech** [comment]
Cảm ơn anh, em dùng csbinary của anh để viết code bên nodejs cho nhanh, port code bên C++ qua nodejs của cái học anh văn, nhưng em vẫn đang tìm hiểu sao mọi người có thể biết seek bao nhiêu byte, lấy bao nhiêu byte, em có dùng IDA để disassmbly về mã giả C++ nhưng trace theo hơi khó khăn, em cần bộ data english để luyện nghe anh văn trên mobile, viết app xong bỏ vào điện thoại nghe cho tiện, với cũng hứng thú cách reverse engineering.

```
function readChunkData(pos, size) {
    let buffer = Buffer.alloc(size);

    dataReader.file.seek(pos, SeekOrigin.Begin);
    dataReader.file.read(buffer, 0, size);

    return buffer;
}
```
